version: '3.8'

services:
  mock-api:
    build: ./mock-api
    ports:
      - "8082:8082"
    networks:
      - backend

  ambassador-proxy:
    build: ./ambassador-proxy
    ports:
      - "8081:8081"
    depends_on:
      - mock-api
    networks:
      - backend

  client-service:
    build: ./client-service
    ports:
      - "8080:8080"
    depends_on:
      - ambassador-proxy
    networks:
      - backend

networks:
    backend:
        driver: bridge
